export const BADGE_ICON_OPTIONS = [
  { value: "Compass", label: "Boussole" },
  { value: "HeartPulse", label: "Secourisme" },
  { value: "Tent", label: "Tente" },
  { value: "ChefHat", label: "Cuisine" },
  { value: "Flame", label: "Feu" },
  { value: "Link", label: "Nœuds" },
  { value: "Hammer", label: "Construction" },
  { value: "Leaf", label: "Nature" },
  { value: "HandHeart", label: "Service" },
  { value: "Crown", label: "Leadership" },
  { value: "Medal", label: "Médaille" },
  { value: "MessageCircle", label: "Communication" },
  { value: "Star", label: "Étoile" },
  { value: "Shield", label: "Bouclier" },
  { value: "Target", label: "Cible" },
  { value: "Map", label: "Carte" },
  { value: "BookOpen", label: "Livre" },
  { value: "Users", label: "Équipe" },
  { value: "TreePine", label: "Forêt" },
  { value: "Mountain", label: "Montagne" },
] as const;

export const BADGE_CATEGORY_OPTIONS = [
  "Orientation",
  "Secourisme",
  "Campisme",
  "Technique",
  "Nature",
  "Service",
  "Leadership",
  "Sport",
  "Communication",
  "Autre",
] as const;
